import type{AdminLog,Team,TeamApplication,Tournament,TournamentApplication,User}from"./types";
export const currentUser:User={id:"u1",firstName:"Анна",lastName:"Сонина",email:"anna@example.ru",phone:"+7 912 345-67-89",telegram:"@annasonina",birthDate:"14.05.2000",role:"ADMIN"};
export const teams:Team[]=["New Dimension","Второе дыхание","Impulse","Cyber Tigers","Steel Mind","Unity"].map((name,i)=>({id:`t${i+1}`,name,discipline:"Баскетбол",members:[{id:"u1",name:i?"Мария Иванова":"Иван Петров",captain:true},{id:"u2",name:"Алексей Смирнов"},{id:"u3",name:"Екатерина Морозова"},{id:"u4",name:"Никита Соколов"}]}));
export const tournaments:Tournament[]=[{id:"phygital-basketball",publicNumber:"#001",name:"Фиджитал Баскетбол",discipline:"Фиджитал-спорт",format:"5×5 · LAN + REAL",city:"Екатеринбург",venue:"Кампус КЦТ",shortDescription:"Реальные броски. Цифровые победы.",description:"Турнир, где физическая игра встречается с киберпространством. Команды проходят реальный и цифровой этапы.",startAt:"2027-10-25T09:00:00+05:00",endAt:"2027-10-27T19:00:00+05:00",registrationEndsAt:"2027-10-20T23:59:00+05:00",rules:["Команда состоит из пяти участников","Результаты двух этапов суммируются","Честная игра обязательна"]},{id:"digital-battle",publicNumber:"#002",name:"Digital Battle",discipline:"Киберспорт",format:"LAN",city:"Москва",venue:"Cyber Arena",shortDescription:"Командный цифровой турнир.",description:"Соревнование по командной цифровой дисциплине.",startAt:"2026-09-01T09:00:00+03:00",endAt:"2026-09-30T19:00:00+03:00",registrationEndsAt:"2026-08-25T23:59:00+03:00",rules:["Состав из пяти игроков"]}];
export const users:User[]=[currentUser,{id:"u2",firstName:"Иван",lastName:"Петров",email:"ivan@mail.ru",phone:"+7 912 345-67-89",telegram:"@ivanpetrov",birthDate:"14.05.2000",role:"USER"},{id:"u3",firstName:"Мария",lastName:"Иванова",email:"maria@mail.ru",phone:"+7 900 123-45-67",telegram:"@maria_iv",birthDate:"10.11.2001",role:"USER"},{id:"u4",firstName:"Алексей",lastName:"Смирнов",email:"alex@mail.ru",phone:"+7 909 111-22-33",telegram:"@smirnov_a",birthDate:"22.03.2000",role:"USER"}];
export const teamApplications:TeamApplication[]=[{id:"4587",proposedName:"Phoenix",captainName:"Иван Петров",membersText:"Иван Петров, Мария Иванова, Алексей Смирнов, Екатерина Морозова",status:"NEW",createdAt:"18.09.2025 14:32"}];
export const tournamentApplications:TournamentApplication[]=[{id:"4587",teamId:"t1",tournamentId:"digital-battle",captainName:"Иван Петров",additionalInfo:"Готовы к участию!",status:"NEW",createdAt:"18.09.2025 14:32"}];
export const logs:AdminLog[]=[{id:"1",date:"18.09.2025 14:32",admin:"Анна Сонина",action:"Создание",entityType:"Пользователь",entityId:"#1024",details:"Создан пользователь Иван Петров"},{id:"2",date:"18.09.2025 13:17",admin:"Анна Сонина",action:"Изменение",entityType:"Команда",entityId:"#56",details:"Изменено название команды"},{id:"3",date:"17.09.2025 16:21",admin:"Мария Котова",action:"Одобрение",entityType:"Заявка",entityId:"#87",details:"Одобрена заявка на турнир"}];
export function tournamentStatus(t:Tournament,now=new Date()):"upcoming"|"active"|"completed"{if(new Date(t.startAt)>now)return"upcoming";if(new Date(t.endAt)>=now)return"active";return"completed"}
