"use client";
/* eslint-disable @next/next/no-img-element */
import { useState, type ReactNode } from "react";
import { ArrowRight, CalendarCheck, ChevronDown, Clock3, ExternalLink, Gamepad2, Handshake, Headphones, Mail, MapPin, MessageSquareText, Phone, RadioTower, Scale, Send, ShieldCheck, Sparkles, Trophy, UsersRound } from "lucide-react";
import { CONTACTS } from "@/shared/config";
import { DemoForm, Field, GlowButton, Modal, PageHero, Reveal, TextareaField } from "@/shared/ui";
import { useApp } from "@/shared/providers";

const rules = [
  { icon: ShieldCheck, title: "Общие положения", text: "Phygital Core объединяет спортивные соревнования и цифровые дисциплины. Правила обязательны для всех участников." },
  { icon: Gamepad2, title: "Формат турнира", text: "Команды проходят групповой этап и плей-офф в реальном и цифровом форматах." },
  { icon: UsersRound, title: "Требования к участникам", text: "Возраст от 16 лет, команда из пяти человек, регистрация и подтверждение участия." },
  { icon: CalendarCheck, title: "Проведение матчей", text: "Расписание публикуется заранее. Участники должны быть на связи и прибыть вовремя." },
  { icon: Scale, title: "Поведение и честная игра", text: "Запрещены читы, оскорбления и неспортивное поведение. Уважение к сопернику — часть результата." },
  { icon: RadioTower, title: "Изменения в правилах", text: "Организатор публикует актуальную версию правил на этой странице и уведомляет участников." },
];
const questions = [
  ["Где проходят мероприятия?", "На базе Кампуса КЦТ в Екатеринбурге. Точная площадка указана на странице турнира."],
  ["Что нужно для участия?", "Зарегистрируйтесь, вступите в команду и подайте заявку на выбранный турнир."],
  ["Как создать команду?", "Отправьте заявку через страницу команд. После одобрения администратор создаёт команду отдельно."],
  ["Как принять участие в турнире?", "Капитан выбирает существующую команду и отправляет заявку. Данные капитана определяются автоматически."],
  ["Как определяется победитель?", "По сумме результатов реального и цифрового этапов в соответствии с правилами конкретного турнира."],
];

function VisualHero({ kind, eyebrow, title, description, src, alt, facts }: { kind: string; eyebrow: string; title: string; description: string; src: string; alt: string; facts: string[] }) {
  return <section className={`editorial-hero ${kind}`}><div className="editorial-copy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p><div className="hero-fact-row">{facts.map((fact, i)=><span key={fact}><b>0{i+1}</b>{fact}</span>)}</div></div><div className="editorial-art"><img src={src} alt={alt}/><i aria-hidden="true"/></div></section>;
}

export function RulesPage() {
  return <><VisualHero kind="rules-hero" eyebrow="ПРАВИЛА ТУРНИРА" title="ЧЕСТНАЯ ИГРА. ЯСНЫЕ ПРАВИЛА." description="Единый регламент соединяет реальную площадку и цифровую арену — без скрытых условий и спорных трактовок." src="/rules-arena.webp" alt="Спортсмен между реальной ареной и цифровой тактической проекцией" facts={["единый регламент", "два этапа", "одна команда"]}/><Reveal><section className="content-section rules-intro"><div><p className="eyebrow">КОДЕКС УЧАСТНИКА</p><h2>Важное — без мелкого шрифта</h2></div><p>Перед подачей заявки ознакомьтесь со всеми разделами. Правила действуют для игроков, капитанов и организаторов.</p></section></Reveal><section className="content-section rules-cards">{rules.map(({icon:Icon,title,text},i)=><Reveal key={title} delay={i*55}><article className="glass"><span className="rule-number">0{i+1}</span><Icon/><div><h2>{title}</h2><p>{text}</p></div></article></Reveal>)}</section><Reveal><section className="content-section rules-banner glass"><Trophy/><div><p className="eyebrow">ГЛАВНЫЙ ПРИНЦИП</p><h2>Победа ценна, когда она честная</h2><p>Сомневаетесь в трактовке пункта? Задайте вопрос до начала матча.</p></div><a className="secondary" href="/faq">Перейти в FAQ <ArrowRight/></a></section></Reveal></>;
}

export function FaqPage() {
  const [open,setOpen]=useState<number|null>(null),[ask,setAsk]=useState(false),{notify}=useApp();
  return <><VisualHero kind="faq-hero" eyebrow="ЦЕНТР ЗНАНИЙ" title="ОТВЕТ НАЙДЁТСЯ." description="Коротко объясняем участие, команды и правила. Если вопрос уникальный — команда поддержки подключится лично." src="/faq-core.webp" alt="Светящееся кристаллическое ядро знаний" facts={["частые вопросы", "быстрые ответы", "живая поддержка"]}/><Reveal><section className="content-section faq-shell"><aside className="faq-aside glass"><MessageSquareText/><p className="eyebrow">FAQ / 01—06</p><h2>Всё по делу</h2><p>Выберите вопрос, чтобы раскрыть ответ. Одновременно открывается только нужный контекст.</p><GlowButton onClick={()=>setAsk(true)}>Задать свой вопрос <Send/></GlowButton></aside><div className="faq-list faq-modern">{questions.map(([q,a],i)=><article className={`glass ${open===i?"open":""}`} key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?null:i)}><span>0{i+1}</span><b>{q}</b><ChevronDown/></button><div className="faq-answer"><p>{a}</p></div></article>)}<article className="glass faq-question"><button onClick={()=>setAsk(true)}><span>06</span><b>Остались вопросы?</b><ArrowRight/></button></article></div></section></Reveal><Reveal><section className="content-section contact-cta glass"><div><p className="eyebrow">НЕ НАШЛИ ОТВЕТ?</p><h2>Сформулируйте вопрос — мы разберёмся</h2><p>Ответ придёт на указанный email.</p></div><GlowButton onClick={()=>setAsk(true)}>Связаться с нами <ArrowRight/></GlowButton></section></Reveal>{ask&&<Modal title="Задать вопрос" subtitle="Заполните форму — мы ответим на указанный email." onClose={()=>setAsk(false)}><DemoForm onSuccess={()=>{setAsk(false);notify("Вопрос отправлен")}}><Field label="Ваше имя" required/><Field label="Email" type="email" required/><label>Тема <b className="required">*</b><select required defaultValue=""><option value="" disabled>Выберите тему</option><option>Участие в турнире</option><option>Регистрация команды</option><option>Правила турнира</option><option>Предложение сотрудничества</option><option>Технические вопросы</option><option>Другое</option></select></label><TextareaField label="Ваш вопрос" required/></DemoForm></Modal>}</>;
}

export function ContactsPage() {
  const {notify}=useApp();
  return <><VisualHero kind="contacts-hero" eyebrow="КАНАЛ СВЯЗИ ОТКРЫТ" title="ДАВАЙТЕ СОЗДАДИМ СЛЕДУЮЩУЮ ИГРУ." description="Вопрос участника, идея партнёра или техническая задача — направим сообщение нужной команде и вернёмся с ответом." src="/contacts-network.webp" alt="Футуристическая сеть связи над технологическим городом" facts={["Екатеринбург", "Пн–Пт 9:00–18:00", "ответ в рабочее время"]}/><Reveal><section className="content-section contact-hub"><div className="contact-channel-grid"><Contact icon={<Phone/>} label="Позвонить" value={CONTACTS.phone} detail="Обсудить участие и организацию" href={CONTACTS.phoneHref}/><Contact icon={<Mail/>} label="Написать" value={CONTACTS.email} detail="Для вопросов и предложений" href={CONTACTS.emailHref}/><Contact icon={<MapPin/>} label="Встретиться" value={CONTACTS.organizer} detail={CONTACTS.address} href={CONTACTS.organizerUrl}/><Contact icon={<Clock3/>} label="Режим работы" value="Пн–Пт 9:00–18:00" detail="Сб–Вс — выходные"/></div><aside className="signal-desk glass"><span className="signal-orbit"><Headphones/></span><p className="eyebrow">SIGNAL DESK</p><h2>Мы на связи</h2><p>Выберите удобный канал или оставьте сообщение в форме ниже.</p><div><a href={CONTACTS.telegram} target="_blank" rel="noreferrer">Telegram <ExternalLink/></a><a href={CONTACTS.vk} target="_blank" rel="noreferrer">VK <ExternalLink/></a></div></aside></section></Reveal><Reveal><section className="content-section contact-form-section glass"><div><p className="eyebrow">ОБРАТНАЯ СВЯЗЬ</p><h2>Расскажите, чем помочь</h2><p>Не передавайте пароли и платёжные данные. Для обращения достаточно имени, email и сути вопроса.</p><ul><li><Sparkles/>Поддержка участников</li><li><Handshake/>Партнёрство и сотрудничество</li><li><RadioTower/>Технические вопросы</li></ul></div><DemoForm onSuccess={()=>notify("Сообщение отправлено")} submit="Отправить сообщение"><Field label="Ваше имя" required/><Field label="Email" type="email" required/><label>Тема <b className="required">*</b><select required defaultValue=""><option value="" disabled>Выберите тему</option><option>Участие в турнире</option><option>Регистрация команды</option><option>Предложение сотрудничества</option><option>Технические вопросы</option><option>Другое</option></select></label><TextareaField label="Сообщение" required/></DemoForm></section></Reveal></>;
}

function Contact({icon,label,value,detail,href}:{icon:ReactNode;label:string;value:string;detail:string;href?:string}) { const body=<>{icon}<span><small>{label}</small><b>{value}</b><em>{detail}</em></span><ArrowRight/></>;return href?<a className="contact-card glass" href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined}>{body}</a>:<div className="contact-card glass">{body}</div>; }

export function PrivacyPage(){return <><PageHero eyebrow="ИНФОРМАЦИЯ" title="ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ" description="Как мы обрабатываем и защищаем персональные данные."/><article className="content-section legal glass"><h2>Общие положения</h2><p>Демонстрационная редакция. Перед публикацией текст должен быть утверждён владельцем платформы.</p><h2>Обрабатываемые данные</h2><p>Имя, email, телефон, сведения профиля и данные, необходимые для участия в турнирах.</p><h2>Ваши права</h2><p>Вы можете запросить уточнение или удаление данных, если их хранение не требуется законодательством.</p></article></>}
