"use client";
import{useEffect,useRef,useState,useSyncExternalStore,type ButtonHTMLAttributes,type FormEvent,type InputHTMLAttributes,type ReactNode}from"react";import{createPortal}from"react-dom";import{Eye,EyeOff,X}from"lucide-react";
export function GlowButton({children,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className="primary" {...props}>{children}</button>}
export function SecondaryButton({children,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className="secondary" {...props}>{children}</button>}
export function PageHero({eyebrow,title,description,visual}:{eyebrow:string;title:string;description:string;visual?:ReactNode}){return <section className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{description}</p></div><div className="page-visual" aria-hidden="true">{visual??"///"}</div></section>}
export function Badge({children,tone="purple"}:{children:ReactNode;tone?:"purple"|"green"|"blue"|"red"}){return <span className={`badge ${tone}`}>{children}</span>}
export function Modal({title,subtitle,children,onClose,busy=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;busy?:boolean}){const ref=useRef<HTMLDivElement>(null),mounted=useSyncExternalStore(()=>()=>{},()=>true,()=>false);useEffect(()=>{if(!mounted)return;const previous=document.activeElement as HTMLElement|null,body=document.body,overflow=body.style.overflow,padding=body.style.paddingRight,scrollbar=window.innerWidth-document.documentElement.clientWidth;body.style.overflow="hidden";if(scrollbar>0)body.style.paddingRight=`${scrollbar}px`;const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy)onClose();if(e.key==="Tab"&&ref.current){const focusable=[...ref.current.querySelectorAll<HTMLElement>("button,input,select,textarea,a[href]")].filter(x=>!x.hasAttribute("disabled"));if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);requestAnimationFrame(()=>ref.current?.querySelector<HTMLElement>("input,button")?.focus());return()=>{document.removeEventListener("keydown",key);body.style.overflow=overflow;body.style.paddingRight=padding;previous?.focus()}},[onClose,busy,mounted]);if(!mounted)return null;return createPortal(<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><div className="modal glass" role="dialog" aria-modal="true" aria-labelledby="modal-title" aria-busy={busy} ref={ref}><button className="close" onClick={onClose} disabled={busy} aria-label="Закрыть"><X/></button><h2 id="modal-title">{title}</h2>{subtitle&&<p>{subtitle}</p>}{children}</div></div>,document.body)}
export function Field({label,type="text",required=false,placeholder}:{label:string;type?:string;required?:boolean;placeholder?:string}){return <label>{label}{required&&<b className="required"> *</b>}<input type={type} required={required} placeholder={placeholder}/></label>}
type PasswordFieldProps=Omit<InputHTMLAttributes<HTMLInputElement>,"type">&{label:string};
export function PasswordField({label,required=false,...inputProps}:PasswordFieldProps){const[visible,setVisible]=useState(false);return <label>{label}{required&&<b className="required"> *</b>}<span className="password-control"><input {...inputProps} type={visible?"text":"password"} required={required}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?"Скрыть пароль":"Показать пароль"}>{visible?<EyeOff/>:<Eye/>}</button></span></label>}
export function TextareaField({label,required=false,maxLength=500}:{label:string;required?:boolean;maxLength?:number}){const[value,setValue]=useState("");return <label>{label}{required&&<b className="required"> *</b>}<textarea required={required} maxLength={maxLength} value={value} onChange={e=>setValue(e.target.value)}/><small>{value.length}/{maxLength}</small></label>}
export function FormActions({submit="Отправить",cancel,onCancel,busy=false}:{submit?:string;cancel?:string;onCancel?:()=>void;busy?:boolean}){return <div className="form-actions">{cancel&&<SecondaryButton type="button" onClick={onCancel} disabled={busy}>{cancel}</SecondaryButton>}<GlowButton type="submit" disabled={busy}>{busy?"Отправка…":`${submit} →`}</GlowButton></div>}
export function DemoForm({children,onSuccess,submit,cancel,onCancel}:{children:ReactNode;onSuccess:()=>void|Promise<void>;submit?:string;cancel?:string;onCancel?:()=>void}){const[busy,setBusy]=useState(false),[error,setError]=useState("");const handle=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{await onSuccess()}catch{setError("Не удалось выполнить действие. Попробуйте ещё раз.")}finally{setBusy(false)}};return <form onSubmit={handle} aria-busy={busy}>{children}{error&&<p className="form-error" role="alert">{error}</p>}<FormActions submit={submit} cancel={cancel} onCancel={onCancel} busy={busy}/></form>}
export function EmptyState({title="Данных пока нет"}:{title?:string}){return <div className="state glass"><h3>{title}</h3><p>Попробуйте обновить страницу позднее.</p></div>}
export function DataTable({headers,rows}:{headers:string[];rows:(string|ReactNode)[][]}){return <div className="data-table glass"><div className="table-row table-head">{headers.map(h=><span key={h}>{h}</span>)}</div>{rows.map((r,i)=><div className="table-row" key={i}>{r.map((c,j)=><span key={j}>{c}</span>)}</div>)}</div>}
